# Site settings
author: Idalis Paz
title: Why Did You Decide to Study Software Engineer?
header-img: img/home-bg.png
email: idalispaz@gmail.com
copyright_name: Idalis Paz
description: > # this means to ignore newlines until "baseurl:"
  Why Did I?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  idalispaz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
